//vary +able=variable
var price =13;
var age=19;
var tomatoo = 20;
var person = "sodor uddin";
var location ="andor killa bandorban";
var special ="alia bhatt";
var serious = true;
var isFull=true;
var isSingle = false;